# Pytorch学习

In [40]:
import torch

## 1. 基本语法

### 1.1 张量

In [41]:
# 张量，类似于np.array
x = torch.Tensor(2, 3, 4)

In [42]:
# 未初始化
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [43]:
x.size()

torch.Size([2, 3, 4])

### 1.2 关于operation（以add为例）

In [44]:
a = torch.rand(2, 3, 4)
b = torch.rand(2, 3, 4)

第一种表达：`torch.add`

In [45]:
# _和x都是返回值
_ = torch.add(a, b, out=x)

In [46]:
_

tensor([[[0.7529, 1.5202, 1.2007, 0.9555],
         [0.9421, 0.9205, 0.9212, 1.4600],
         [0.2614, 1.4642, 0.5818, 0.8120]],

        [[0.4887, 0.9075, 1.7547, 1.0557],
         [0.2859, 0.8574, 1.1486, 1.1477],
         [1.7011, 1.0521, 1.4676, 0.6632]]])

In [47]:
x

tensor([[[0.7529, 1.5202, 1.2007, 0.9555],
         [0.9421, 0.9205, 0.9212, 1.4600],
         [0.2614, 1.4642, 0.5818, 0.8120]],

        [[0.4887, 0.9075, 1.7547, 1.0557],
         [0.2859, 0.8574, 1.1486, 1.1477],
         [1.7011, 1.0521, 1.4676, 0.6632]]])

第二种：`a.add(b)`

In [48]:
a.add(b)

tensor([[[0.7529, 1.5202, 1.2007, 0.9555],
         [0.9421, 0.9205, 0.9212, 1.4600],
         [0.2614, 1.4642, 0.5818, 0.8120]],

        [[0.4887, 0.9075, 1.7547, 1.0557],
         [0.2859, 0.8574, 1.1486, 1.1477],
         [1.7011, 1.0521, 1.4676, 0.6632]]])

In [49]:
a

tensor([[[0.5296, 0.9916, 0.8949, 0.1198],
         [0.1439, 0.8156, 0.2622, 0.6721],
         [0.2001, 0.9352, 0.0633, 0.1639]],

        [[0.3814, 0.5918, 0.8751, 0.4203],
         [0.1515, 0.1049, 0.2912, 0.6927],
         [0.7656, 0.2812, 0.7809, 0.0597]]])

第三种：`a.add_(b)`，所有带 _ 的operation，都会更改调用对象的值

In [50]:
a.add_(b)

tensor([[[0.7529, 1.5202, 1.2007, 0.9555],
         [0.9421, 0.9205, 0.9212, 1.4600],
         [0.2614, 1.4642, 0.5818, 0.8120]],

        [[0.4887, 0.9075, 1.7547, 1.0557],
         [0.2859, 0.8574, 1.1486, 1.1477],
         [1.7011, 1.0521, 1.4676, 0.6632]]])

In [51]:
a

tensor([[[0.7529, 1.5202, 1.2007, 0.9555],
         [0.9421, 0.9205, 0.9212, 1.4600],
         [0.2614, 1.4642, 0.5818, 0.8120]],

        [[0.4887, 0.9075, 1.7547, 1.0557],
         [0.2859, 0.8574, 1.1486, 1.1477],
         [1.7011, 1.0521, 1.4676, 0.6632]]])

In [52]:
torch.cuda.is_available()

True

### 1.3. 其他运算

In [53]:
import numpy as np

data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)
print('\nabs', '\nnumpy: ', np.abs(data),'\ntorch: ', torch.abs(tensor))


abs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])


In [54]:
print('\nmean', '\nnumpy: ', np.mean(data),'\ntorch: ', torch.mean(tensor))


mean 
numpy:  0.0 
torch:  tensor(0.)


In [55]:
print('\nsin', '\nnumpy: ', np.sin(data),'\ntorch: ', torch.sin(tensor))


sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])


矩阵乘法需要特别注意！

In [56]:
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)
# 正确方法
print('matrix',
     '\nnumpy: ', np.matmul(data, data),
     '\ntorch: ', torch.mm(tensor, tensor))

matrix 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]])


In [59]:
tensor.shape

torch.Size([2, 2])

In [61]:
# 错误方法, torch.dot只能用于1维的向量
data = np.array(data)
print('matrix',
     '\nnumpy: ', data.dot(data),
     '\ntorch: ', torch.dot(tensor.squeeze(), tensor.squeeze()))

RuntimeError: dot: Expected 1-D argument self, but got 2-D

## 2. Variable

### 2.1. 定义

In [63]:
import torch
from torch.autograd import Variable # 这里是模块

In [64]:
tensor = torch.FloatTensor([[1,2], [3,4]])
# requires_grad表示是否参与 BP，要不要计算梯度
variable = Variable(tensor, requires_grad=True)

In [65]:
print(tensor)

tensor([[1., 2.],
        [3., 4.]])


In [66]:
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


### 2.2. 对比Tensor和Variable的计算

In [67]:
t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward1>)


事实上`Variable`在计算的时候在搭建一个计算图，`v_out = torch.mean(variable*variable)`在计算图中添加了一个计算步骤，BP执行的时候它会做出贡献

In [68]:
v_out.backward()

In [69]:
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


### 2.3. 获取Variable数据

In [70]:
# Variable形式
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [71]:
# Tensor形式
print(variable.data)

tensor([[1., 2.],
        [3., 4.]])


In [72]:
# numpy形式
print(variable.data.numpy())

[[1. 2.]
 [3. 4.]]


## 3. 关于一些常用函数的说明

### 3.1. `view()`

`view()`函数的作用是reshape，通常用来将一个多行的Tensor，拼接成一行，比如CNN中在数据进入FC之前，通常有一个Flat操作来，用的就是这个`view()`，`view(m, n)`就会得到一个m*n的Tensor，通常m用1，n用-1表示压成一维。

In [73]:
a = torch.Tensor([[1,2,3],[4,5,6]])

In [74]:
a.shape

torch.Size([2, 3])

In [75]:
# 注意是顺序填充
a.view(3,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [76]:
# 通常用1和-1来压平
a.view(1, -1)

tensor([[1., 2., 3., 4., 5., 6.]])

### 3.2. `squeeze()`

`squeeze()`的作用顾名思义，就是挤压，比如如果是一个高维的张量，最高维的维度如果是1，就和比它低1维的张量没什么区别，所以就可以压缩所有为1的维。
前面指的是不给`squeeze()`传参的执行，也可以传参，参数为从0开始的整数，表示维度，它会检查相应的维是否维度为1，然后决定是否压缩，其他的位置不受影响。

In [77]:
a = torch.Tensor([[[[[1,2,3]], [[2,3,4]]]]])
print(a)
print(a.shape)

tensor([[[[[1., 2., 3.]],

          [[2., 3., 4.]]]]])
torch.Size([1, 1, 2, 1, 3])


In [78]:
b = a.squeeze()
print(b)
print(b.shape)

tensor([[1., 2., 3.],
        [2., 3., 4.]])
torch.Size([2, 3])


In [79]:
b = a.squeeze(3)
print(b)
print(b.shape)

tensor([[[[1., 2., 3.],
          [2., 3., 4.]]]])
torch.Size([1, 1, 2, 3])


### 3.3. `unsqueeze()`

`unsqueeze()`的作用和`squeeze()`相反，即拓展维，维度为1，但参数的意思是一样的，不一样的地方在于`unsqueeze()`必须要传参。

In [80]:
a = torch.Tensor([[[[[1,2,3]], [[2,3,4]]]]])
print(a)
print(a.shape)

tensor([[[[[1., 2., 3.]],

          [[2., 3., 4.]]]]])
torch.Size([1, 1, 2, 1, 3])


In [88]:
b = a.unsqueeze(0)
print(b)
print(b.shape)

tensor([[[[[[1., 2., 3.]],

           [[2., 3., 4.]]]]]])
torch.Size([1, 1, 1, 2, 1, 3])


### 3.3. torch.linspace()

`torch.linspace(x, y, z)`是一个静态方法，作用是创建一个等分的Tensor，从x到y，维数是z。

In [91]:
x = torch.linspace(-1, 1, 11)
print(x)
print(x.shape)

tensor([-1.0000, -0.8000, -0.6000, -0.4000, -0.2000,  0.0000,  0.2000,  0.4000,
         0.6000,  0.8000,  1.0000])
torch.Size([11])
